version: '2'

services:
  ca.root:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.root
      - FABRIC_CA_SERVER_TLS_ENABLED=false
      - FABRIC_LOGGING_SPEC=debug
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start  -b adminCA:adminpw -d'
    container_name: ca.root

  ica.dummyOrg:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server-config
      - FABRIC_CA_SERVER_CA_NAME=ica.dummyOrg
      - FABRIC_CA_SERVER_TLS_ENABLED=false
      - FABRIC_LOGGING_SPEC=debug
    ports:
      - "8054:7054"
    command: sh -c 'fabric-ca-server start  -b admin:adminpw -d -u http://ica.dummyOrg:adminpw@${IP_ROOT}:7054'
    volumes:  
     - ./certsICA:/etc/hyperledger/fabric-ca-server
     - ./certsICA:/etc/hyperledger/fabric-ca-server-config
    container_name: ica.dummyOrg


