version: '2'

services:

  

###############################################################
###################### Ordering Service #######################
###############################################################
  orderer0.myapp.com:
    extends:
      file:   base/docker-compose-ordering.yaml
      service: orderer0.myapp.com
    volumes:
      - ./crypto-config/ordererOrganizations/myapp.com/orderers/orderer.myapp.com/msp:/var/hyperledger/orderer/msp
    container_name: orderer0.myapp.com

    
###############################################################
############################ Peers ############################
###############################################################
  peer0.dummyOrg.com:
    container_name: peer0.dummyOrg.com
    extends:
      file:  base/docker-compose-peer.yaml
      service: peer0.dummyOrg.com
    volumes:
      - ./crypto-config/peerOrganizations/dummyOrg.com/peers/peer0.dummyOrg.com/msp:/var/hyperledger/orderer/msp
    depends_on:
      - orderer0.myapp.com
  

###############################################################
############################ CLI ##############################
############################################################### 
  cli:
    container_name: cli
    image: hyperledger/fabric-tools
    tty: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
     # - CORE_LOGGING_LEVEL=DEBUG
      - FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.dummyOrg.com:7051
      - CORE_PEER_LOCALMSPID=dummyOrgMSP
      - CORE_PEER_TLS_ENABLED=false
      # - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/dummyOrg.com/peers/peer0.dummyOrg.com/tls/MyCertificate.crt
      # - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/dummyOrg.com/peers/peer0.dummyOrg.com/tls/MyKey.key
      # - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/dummyOrg.com/ca/ica.dummyOrg.com.crt.pem
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/dummyOrg.com/users/Admin@dummyOrg.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    volumes:
        - /var/run/:/host/var/run/
        - ./chaincodes/:/opt/gopath/src/github.com/hyperledger/fabric/examples/chaincode/go
        - ./crypto-config/:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./scripts/:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - orderer0.myapp.com
      - peer0.dummyOrg.com
